contact_links:
  - name: Twilio SendGrid Support
    url: https://support.sendgrid.com
    about: Get Support
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/sendgrid
    about: Ask questions on Stack Overflow
  - name: python Language Documentation
    url: https://www.twilio.com/docs/libraries/reference/sendgrid-python/
    about: View Reference Documentation
