contact_links:
  - name: Twilio Support
    url: https://support.twilio.com
    about: Get Support
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/twilio
    about: Ask questions on Stack Overflow
  - name: Python Language Documentation
    url: https://www.twilio.com/docs/libraries/reference/twilio-python/
    about: View Reference Documentation
